name: Terraform CI

on:
  workflow_dispatch:
  #pull_request:
  #  paths:
  #    - '**/*.tf'
  #  types: [opened, synchronize]
  #push:
  #  branches: [main]

jobs:
  Plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      TF_VERSION: 1.5.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ matrix.folder }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ matrix.folder }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ matrix.folder }}
        run: terraform plan -out=tfplan

      - name: Upload Plan (PR context)
        #if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: plan-${{ matrix.folder }}
          path: ${{ matrix.folder }}/tfplan
    strategy:
      matrix:
        folder:
          - 01-local-random-password
          - 02-null-local-exec
          - 03-local-create-file
          
  Apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: Plan
    #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          
      - name: Terraform Init & Apply
        working-directory: ${{ matrix.folder }}
        run: |
          terraform init
          terraform apply -auto-approve

