name: Create Resource

on:
  workflow_dispatch:
  
  #pull_request:
  #  paths:
  #    - '**/*.tf'
  #  types: [opened, synchronize]
  #push:
  #  branches: [main]
  
env:
  TF_VERSION: "1.5.0"
  
jobs:
  Plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        #working-directory: ${{ matrix.folder }}
        run: terraform init

      - name: Terraform Validate
        #working-directory: ${{ matrix.folder }}
        run: terraform validate

      - name: Terraform Plan
        #working-directory: ${{ matrix.folder }}
        run: |
          cd terraform/
          terraform plan -out=tfplan

          
          
